const $=s=>document.querySelector(s), apiBase='';
const state={token:localStorage.getItem('haafiz_token'),user:null,config:{},view:'today',courses:[],tasks:[],mastery:[]};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const res=await fetch(apiBase+path,{...options,headers});let data={};try{data=await res.json()}catch{}if(!res.ok){if(res.status===401&&state.user)logout();throw new Error(data.detail||'Something went wrong')}return data}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function initials(name){return name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}
async function init(){try{state.config=await api('/api/config');applyConfig()}catch{}if(state.token){try{state.user=await api('/api/me');showApp()}catch{logout()}}}
function applyConfig(){document.documentElement.style.setProperty('--primary',state.config.primary_color||'#5b4be8');document.title=`${state.config.site_name||'HAAFIZ'} — Learn with clarity`}
let authMode='login';document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{authMode=b.dataset.mode;document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));const reg=authMode==='register';$('#nameField').hidden=!reg;$('#roleField').hidden=!reg;$('#authTitle').textContent=reg?'Create your learning space':'Continue your learning';$('#authIntro').textContent=reg?'A focused plan, built around what you need.':'Sign in to pick up exactly where you left off.';$('#authSubmit').innerHTML=reg?'Create my account <span>→</span>':'Sign in securely <span>→</span>';$('#password').autocomplete=reg?'new-password':'current-password'});
$('#showPassword').onclick=()=>{const p=$('#password');p.type=p.type==='password'?'text':'password';$('#showPassword').textContent=p.type==='password'?'Show':'Hide'};
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#formError').textContent='';const body={email:$('#email').value,password:$('#password').value};if(authMode==='register')Object.assign(body,{name:$('#name').value,role:$('#role').value});try{const r=await api(`/api/auth/${authMode}`,{method:'POST',body:JSON.stringify(body)});state.token=r.token;state.user=r.user;localStorage.setItem('haafiz_token',r.token);showApp()}catch(err){$('#formError').textContent=err.message}};
const studentNav=[['LEARN',['today','⌂','Today'],['courses','▤','My courses'],['mastery','◎','Mastery map'],['planner','□','Study planner']],['SUPPORT',['tutor','✦','AI tutor'],['library','◇','My library']]];
const teacherNav=[['TEACH',['today','⌂','Overview'],['courses','▤','Courses'],['students','♙','Students']],['INSIGHTS',['mastery','◎','Class mastery'],['planner','□','Assignments']]];
const adminNav=[['CONTROL CENTER',['admin','⌂','Overview'],['users','♙','Users'],['manage-courses','▤','Courses'],['settings','⚙','Configuration']],['GOVERNANCE',['audit','↗','Audit log'],['today','◈','Student view']]];
function showApp(){$('#auth').hidden=true;$('#app').hidden=false;$('#profileName').textContent=state.user.name;$('#profileRole').textContent=state.user.role;$('#avatar').textContent=initials(state.user.name);$('#brandName').firstChild.textContent=state.config.site_name||'HAAFIZ';state.view=state.user.role==='admin'?'admin':'today';renderNav();navigate(state.view)}
function renderNav(){const groups=state.user.role==='admin'?adminNav:state.user.role==='teacher'?teacherNav:studentNav;$('#nav').innerHTML=groups.map(g=>`<p class="nav-group">${g[0]}</p>${g.slice(1).map(x=>`<button class="nav-link ${x[0]===state.view?'active':''}" data-view="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('')}`).join('');document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>navigate(b.dataset.view))}
const titles={today:'Today',courses:'My courses',mastery:'Mastery map',planner:'Study planner',tutor:'Socratic tutor',library:'My library',admin:'Control center',users:'User management','manage-courses':'Course management',settings:'Platform configuration',audit:'Audit log',students:'Students'};
async function navigate(view){state.view=view;$('#pageTitle').textContent=titles[view]||'HAAFIZ';$('#crumb').textContent=state.user.role==='admin'?'ADMINISTRATION':'YOUR LEARNING SPACE';renderNav();$('#sidebar').classList.remove('open');$('#view').innerHTML='<div class="empty">Loading your space…</div>';try{if(view==='today')await renderToday();else if(view==='courses')await renderCourses();else if(view==='mastery')await renderMastery();else if(view==='planner')await renderPlanner();else if(view==='admin')await renderAdmin();else if(view==='users')await renderUsers();else if(view==='manage-courses')await renderManageCourses();else if(view==='settings')await renderSettings();else if(view==='audit')await renderAudit();else renderComing(view)}catch(e){$('#view').innerHTML=`<div class="empty"><b>We couldn't load this page.</b><br>${esc(e.message)}</div>`}}
async function renderToday(){const [d,c,t]=await Promise.all([api('/api/dashboard'),api('/api/courses'),api('/api/tasks')]);state.courses=c;state.tasks=t;const enrolled=c.filter(x=>x.enrolled);$('#view').innerHTML=`<section class="welcome"><div><h1>Assalam-o-alaikum, ${esc(state.user.name.split(' ')[0])} 👋</h1><p>Let's make one meaningful step today.</p></div><span class="pill">${new Date().toLocaleDateString('en-PK',{weekday:'long',day:'numeric',month:'long'})}</span></section><section class="action"><div><small>YOUR RECOMMENDED NEXT STEP</small><h3>${esc(d.next_action)}</h3><p>${d.average_mastery?`Based on your ${d.average_mastery}% average concept mastery.`:'Choose a course to build your personal mastery map.'}</p></div><button class="btn" onclick="navigate('courses')">${enrolled.length?'Continue learning':'Explore courses'} →</button></section><section class="metrics"><article class="metric"><small>ENROLLED COURSES</small><strong>${d.courses}</strong><span>Your active learning paths</span></article><article class="metric"><small>AVERAGE MASTERY</small><strong>${d.average_mastery}%</strong><span>${d.average_mastery?'From real attempts':'Awaiting practice data'}</span></article><article class="metric"><small>TASKS DUE</small><strong>${d.tasks_due}</strong><span>Keep today's plan realistic</span></article><article class="metric"><small>FOCUS STATUS</small><strong>${d.tasks_due>4?'Busy':'On track'}</strong><span>Based on your current plan</span></article></section><div class="grid"><section class="panel"><div class="panel-head"><div><h3>Continue learning</h3><p>Your enrolled courses and current progress</p></div><button class="link" onclick="navigate('courses')">View all →</button></div>${enrolled.length?enrolled.map(courseRow).join(''):'<div class="empty">No course yet. Start with one focused subject.</div>'}</section><section class="panel"><div class="panel-head"><div><h3>Today’s plan</h3><p>${t.filter(x=>!x.completed).length} tasks waiting</p></div><button class="link" onclick="navigate('planner')">Plan →</button></div>${t.length?t.slice(0,5).map(taskRow).join(''):'<div class="empty">Your day is clear. Add one achievable task.</div>'}</section></div>`}
function courseRow(c){return `<article class="course-row"><span class="course-icon" style="color:${c.accent};background:${c.accent}15">${esc(c.code.slice(0,2))}</span><div><h4>${esc(c.title)}</h4><p>${esc(c.code)} · ${c.progress}% complete</p><div class="progress"><i style="width:${c.progress}%;background:${c.accent}"></i></div></div><button class="pill">Resume</button></article>`}
function taskRow(t){return `<article class="task"><button class="${t.completed?'done':''}" onclick="toggleTask(${t.id})" aria-label="Toggle ${esc(t.title)}">${t.completed?'✓':''}</button><div><b>${esc(t.title)}</b><small>${esc(t.subject)} · ${t.duration} min</small></div></article>`}
async function renderCourses(){state.courses=await api('/api/courses');$('#view').innerHTML=`<div class="section-title"><div><h1>Build your learning path</h1><p>Choose deliberately. You can always add another subject later.</p></div></div><div class="cards">${state.courses.map(c=>`<article class="course-card"><span class="course-icon" style="color:${c.accent};background:${c.accent}15">${esc(c.code.slice(0,2))}</span><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><footer><span class="subtle">${esc(c.code)}</span>${c.enrolled?'<span class="pill">Enrolled</span>':`<button class="btn primary" onclick="enroll(${c.id})">Add course</button>`}</footer></article>`).join('')}</div>`}
async function enroll(id){await api(`/api/courses/${id}/enroll`,{method:'POST'});toast('Course added to your learning path');renderCourses()}
async function renderMastery(){state.mastery=await api('/api/mastery');$('#view').innerHTML=`<div class="section-title"><div><h1>Mastery, made understandable</h1><p>Estimates use your practice evidence—never fabricated scores.</p></div></div><section class="panel"><div class="panel-head"><div><h3>Concept map</h3><p>Why these scores? Each correct or incorrect attempt updates your estimate.</p></div></div>${state.mastery.length?state.mastery.map(m=>`<article class="mastery-row"><div><h4>${esc(m.concept)}</h4><small>${esc(m.course)} · ${m.attempts} evidence point${m.attempts===1?'':'s'}</small></div><div class="mastery-bar"><i style="width:${m.mastery_percent}%"></i></div><strong>${m.attempts?m.mastery_percent+'%':'Not enough data'}</strong></article>`).join(''):'<div class="empty">Enroll in a course to create your mastery map.</div>'}</section>`}
async function renderPlanner(){state.tasks=await api('/api/tasks');$('#view').innerHTML=`<div class="section-title"><div><h1>A realistic plan for your day</h1><p>Keep tasks small enough to finish with focus.</p></div><button class="btn primary" onclick="taskModal()">＋ Add task</button></div><section class="panel">${state.tasks.length?state.tasks.map(taskRow).join(''):'<div class="empty">No tasks yet. Add your first focused session.</div>'}</section>`}
function taskModal(){modal(`<h2>Add a focused task</h2><form id="taskForm"><label>What will you work on?</label><input id="taskTitle" required placeholder="e.g. Practice integration questions"><label>Subject</label><input id="taskSubject" required placeholder="Mathematics"><label>When?</label><input id="taskDue" type="datetime-local" required><label>Focus minutes</label><input id="taskDuration" type="number" value="25" min="5" max="300"><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary">Add to plan</button></div></form>`);$('#taskForm').onsubmit=async e=>{e.preventDefault();await api('/api/tasks',{method:'POST',body:JSON.stringify({title:$('#taskTitle').value,subject:$('#taskSubject').value,due_at:new Date($('#taskDue').value).toISOString(),duration:+$('#taskDuration').value})});closeModal();toast('Task added to your plan');renderPlanner()}}
async function toggleTask(id){await api(`/api/tasks/${id}/toggle`,{method:'PATCH'});state.view==='today'?renderToday():renderPlanner()}
async function renderAdmin(){const d=await api('/api/admin/overview');$('#view').innerHTML=`<div class="section-title"><div><h1>Platform at a glance</h1><p>See what needs attention, then act with confidence.</p></div></div><section class="admin-layout">${[['Users',d.counts.users],['Courses',d.counts.courses],['Enrollments',d.counts.enrollments],['Concepts',d.counts.concepts]].map(x=>`<article class="metric"><small>${x[0].toUpperCase()}</small><strong>${x[1]}</strong><span>Live platform total</span></article>`).join('')}</section><section class="panel" style="margin-top:20px"><div class="panel-head"><div><h3>Recent administration</h3><p>Accountable changes across the platform</p></div></div>${d.recent_activity.length?auditTable(d.recent_activity):'<div class="empty">No administrative changes yet.</div>'}</section>`}
async function renderUsers(){const users=await api('/api/admin/users');$('#view').innerHTML=`<div class="section-title"><div><h1>People and access</h1><p>Role-based access keeps every workspace relevant and secure.</p></div></div><section class="panel"><table class="admin-table"><thead><tr><th>PERSON</th><th>EMAIL</th><th>ROLE</th><th>JOINED</th></tr></thead><tbody>${users.map(u=>`<tr><td><b>${esc(u.name)}</b></td><td>${esc(u.email)}</td><td><select onchange="changeRole(${u.id},this.value)" ${u.id===state.user.id?'disabled':''}>${['student','teacher','admin'].map(r=>`<option ${u.role===r?'selected':''}>${r}</option>`).join('')}</select></td><td>${new Date(u.created_at).toLocaleDateString()}</td></tr>`).join('')}</tbody></table></section>`}
async function changeRole(id,role){try{await api(`/api/admin/users/${id}/role`,{method:'PATCH',body:JSON.stringify({role})});toast('Access role updated')}catch(e){toast(e.message);renderUsers()}}
async function renderManageCourses(){const courses=await api('/api/courses');$('#view').innerHTML=`<div class="section-title"><div><h1>Courses and curriculum</h1><p>Create and maintain learning paths without touching code.</p></div><button class="btn primary" onclick="courseModal()">＋ New course</button></div><section class="panel">${courses.map(courseRow).join('')}</section>`}
function courseModal(){modal(`<h2>Create a course</h2><form id="courseForm"><label>Course title</label><input id="courseTitle" required><label>Short code</label><input id="courseCode" required placeholder="BIO-12"><label>Description</label><textarea id="courseDescription" rows="3"></textarea><label>Accent colour</label><input id="courseAccent" type="color" value="#5b4be8"><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary">Create course</button></div></form>`);$('#courseForm').onsubmit=async e=>{e.preventDefault();await api('/api/admin/courses',{method:'POST',body:JSON.stringify({title:$('#courseTitle').value,code:$('#courseCode').value,description:$('#courseDescription').value,accent:$('#courseAccent').value})});closeModal();toast('Course created');renderManageCourses()}}
async function renderSettings(){const settings=await api('/api/admin/settings');const grouped=Object.groupBy?Object.groupBy(settings,x=>x.category):settings.reduce((a,x)=>((a[x.category]??=[]).push(x),a),{});$('#view').innerHTML=`<div class="section-title"><div><h1>Configure without code</h1><p>Features, access and branding are controlled here and audited.</p></div></div>${Object.entries(grouped).map(([cat,items])=>`<section class="panel" style="margin-bottom:18px"><div class="panel-head"><div><h3>${esc(cat[0].toUpperCase()+cat.slice(1))}</h3></div></div><div class="settings">${items.map(s=>`<label class="setting"><span><b>${esc(s.label)}</b><small>${esc(s.key)}</small></span>${s.kind==='boolean'?`<input class="switch" type="checkbox" ${s.value==='true'?'checked':''} onchange="saveSetting('${s.key}',this.checked?'true':'false')">`:`<input type="${s.kind==='color'?'color':s.kind==='email'?'email':'text'}" value="${esc(s.value)}" onchange="saveSetting('${s.key}',this.value)">`}</label>`).join('')}</div></section>`).join('')}`}
async function saveSetting(key,value){await api(`/api/admin/settings/${key}`,{method:'PATCH',body:JSON.stringify({value})});toast('Setting saved and logged');if(key==='primary_color'||key==='site_name'){state.config=await api('/api/config');applyConfig()}}
async function renderAudit(){const logs=await api('/api/admin/audit');$('#view').innerHTML=`<div class="section-title"><div><h1>Audit trail</h1><p>A clear record of sensitive administrative actions.</p></div></div><section class="panel">${logs.length?auditTable(logs):'<div class="empty">No changes recorded.</div>'}</section>`}
function auditTable(logs){return `<table class="admin-table"><thead><tr><th>WHEN</th><th>ACTOR</th><th>ACTION</th><th>RESOURCE</th><th>DETAIL</th></tr></thead><tbody>${logs.map(l=>`<tr><td>${new Date(l.created_at).toLocaleString()}</td><td>${esc(l.actor||'System')}</td><td>${esc(l.action)}</td><td>${esc(l.entity)} ${esc(l.entity_id||'')}</td><td>${esc(l.details)}</td></tr>`).join('')}</tbody></table>`}
function renderComing(view){$('#view').innerHTML=`<div class="section-title"><div><h1>${esc(titles[view]||view)}</h1><p>This capability is intentionally disabled until its validated service is connected.</p></div></div><div class="empty"><b>Safe placeholder—not fake functionality.</b><br>The administrator can control availability from Platform configuration.</div>`}
function modal(html){const d=document.createElement('div');d.className='modal';d.id='modal';d.innerHTML=`<div class="modal-card">${html}</div>`;document.body.appendChild(d)}function closeModal(){$('#modal')?.remove()}
function logout(){localStorage.removeItem('haafiz_token');state.token=null;state.user=null;$('#app').hidden=true;$('#auth').hidden=false}$('#logout').onclick=logout;$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');window.navigate=navigate;window.enroll=enroll;window.toggleTask=toggleTask;window.taskModal=taskModal;window.courseModal=courseModal;window.closeModal=closeModal;window.changeRole=changeRole;window.saveSetting=saveSetting;init();