import React, { FormEvent, useEffect, useRef, useState } from 'react';
import ReactDOM from 'react-dom/client';
import './styles.css';

type Language = 'en' | 'roman';
type DocumentRecord = {document_id:string;original_name:string;mime_type:string;size_bytes:number;page_count:number|null;language_detected:string;status:'queued'|'processing'|'success'|'failed';error_message:string|null;created_at:string};
type UploadResult = {job_id:string;status:string;files:Array<{file_id:string;original_name:string;status:string}>;message:string};
const copy={
  en:{kicker:'YOUR KNOWLEDGE, MADE LEARNABLE',title:'Turn your notes into a learning path.',body:'Upload your own study material. HAAFIZ extracts only the source text first—concept intelligence comes in the next verified step.',signIn:'Sign in',register:'Create account',name:'Full name',email:'Email address',password:'Password',submitLogin:'Continue securely',submitRegister:'Create my workspace',uploadTitle:'Add study material',uploadBody:'PDF, DOCX, PPTX or clear images. Up to 10 files, 50 MB each.',choose:'Choose files',upload:'Upload & process',documents:'Your documents',empty:'No documents yet. Your first upload will appear here.',logout:'Sign out'},
  roman:{kicker:'AAP KA CONTENT, AAP KA LEARNING PATH',title:'Apne notes ko learning path mein badlein.',body:'Apna study material upload karein. HAAFIZ pehle sirf asal text extract karta hai—concept intelligence aglay verified step mein aaye gi.',signIn:'Sign in',register:'Account banayein',name:'Poora naam',email:'Email address',password:'Password',submitLogin:'Securely continue karein',submitRegister:'Workspace banayein',uploadTitle:'Study material add karein',uploadBody:'PDF, DOCX, PPTX ya clear images. 10 files tak, har file 50 MB.',choose:'Files select karein',upload:'Upload aur process',documents:'Aap ke documents',empty:'Abhi koi document nahi. Pehli upload yahan nazar aaye gi.',logout:'Sign out'},
};

async function request<T>(path:string, options:RequestInit={}, token?:string|null):Promise<T>{
  const headers=new Headers(options.headers); if(token)headers.set('Authorization',`Bearer ${token}`); if(options.body && !(options.body instanceof FormData))headers.set('Content-Type','application/json');
  const response=await fetch(path,{...options,headers}); const data=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(data.message||'Request failed. Please try again.'); return data as T;
}

function App():React.JSX.Element{
  const [language,setLanguage]=useState<Language>('en'); const t=copy[language];
  const [token,setToken]=useState<string|null>(()=>localStorage.getItem('haafiz_token'));
  const [authMode,setAuthMode]=useState<'login'|'register'>('login'); const [authError,setAuthError]=useState('');
  const [documents,setDocuments]=useState<DocumentRecord[]>([]); const [selected,setSelected]=useState<File[]>([]); const [busy,setBusy]=useState(false); const [progress,setProgress]=useState(0); const [notice,setNotice]=useState(''); const inputRef=useRef<HTMLInputElement>(null);
  const loadDocuments=async()=>{if(!token)return;try{const result=await request<{items:DocumentRecord[]}>('/api/v1/documents?page_size=100',{},token);setDocuments(result.items)}catch(error){setNotice(error instanceof Error?error.message:'Unable to load documents.')}};
  useEffect(()=>{void loadDocuments()},[token]);
  useEffect(()=>{if(!token||!documents.some(item=>['queued','processing'].includes(item.status)))return;const id=window.setInterval(()=>void loadDocuments(),3000);return()=>clearInterval(id)},[token,documents]);
  const authenticate=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setAuthError('');const form=new FormData(event.currentTarget);try{const result=await request<{access_token:string}>(`/api/v1/auth/${authMode}`,{method:'POST',body:JSON.stringify({name:form.get('name'),email:form.get('email'),password:form.get('password')})});localStorage.setItem('haafiz_token',result.access_token);setToken(result.access_token)}catch(error){setAuthError(error instanceof Error?error.message:'Authentication failed.')}};
  const upload=async()=>{if(!selected.length||!token)return;setBusy(true);setProgress(8);setNotice('');const body=new FormData();selected.forEach(file=>body.append('files',file));let timer=window.setInterval(()=>setProgress(value=>Math.min(value+7,88)),250);try{const result=await request<UploadResult>('/api/v1/documents/upload',{method:'POST',body},token);setProgress(100);setNotice(result.message);setSelected([]);if(inputRef.current)inputRef.current.value='';await loadDocuments()}catch(error){setNotice(error instanceof Error?error.message:'Upload failed.')}finally{window.clearInterval(timer);window.setTimeout(()=>setProgress(0),800);setBusy(false)}};
  const logout=()=>{localStorage.removeItem('haafiz_token');setToken(null);setDocuments([])};
  if(!token)return <main className="auth"><section className="story"><div className="brand"><b>H</b><span>HAAFIZ<small>LEARN WITH CLARITY</small></span></div><div><p className="eyebrow">{t.kicker}</p><h1>{t.title}</h1><p className="lead">{t.body}</p><ul><li>Private, student-owned source files</li><li>English + Urdu OCR pipeline</li><li>No fabricated text or AI results</li></ul></div></section><section className="authPanel"><div className="language"><button className={language==='en'?'active':''} onClick={()=>setLanguage('en')}>English</button><button className={language==='roman'?'active':''} onClick={()=>setLanguage('roman')}>Roman Urdu</button></div><form onSubmit={authenticate}><p className="eyebrow">WELCOME TO HAAFIZ</p><h2>{authMode==='login'?t.signIn:t.register}</h2><div className="tabs"><button type="button" className={authMode==='login'?'active':''} onClick={()=>setAuthMode('login')}>{t.signIn}</button><button type="button" className={authMode==='register'?'active':''} onClick={()=>setAuthMode('register')}>{t.register}</button></div>{authMode==='register'&&<label>{t.name}<input name="name" minLength={2} required autoComplete="name"/></label>}<label>{t.email}<input name="email" type="email" required autoComplete="email"/></label><label>{t.password}<input name="password" type="password" minLength={8} required autoComplete={authMode==='login'?'current-password':'new-password'}/></label>{authError&&<p className="error" role="alert">{authError}</p>}<button className="primary full">{authMode==='login'?t.submitLogin:t.submitRegister}<span>→</span></button></form></section></main>;
  return <div className="app"><header><div className="brand dark"><b>H</b><span>HAAFIZ<small>LEARN WITH CLARITY</small></span></div><nav><button onClick={()=>setLanguage(language==='en'?'roman':'en')}>{language==='en'?'Roman Urdu':'English'}</button><button onClick={logout}>{t.logout}</button></nav></header><main className="workspace"><section className="welcome"><p className="eyebrow">SOURCE LIBRARY</p><h1>{t.uploadTitle}</h1><p>{t.uploadBody}</p></section><section className="uploadCard"><div className="drop"><span aria-hidden="true">↑</span><div><b>{selected.length?`${selected.length} file${selected.length>1?'s':''} selected`:t.choose}</b><small>{selected.length?selected.map(file=>file.name).join(' · '):'PDF · DOCX · PPTX · JPG · PNG · TIFF · BMP'}</small></div><input ref={inputRef} type="file" multiple accept=".pdf,.docx,.pptx,.jpg,.jpeg,.png,.tif,.tiff,.bmp" onChange={event=>setSelected(Array.from(event.target.files||[]))}/></div><button className="primary" disabled={!selected.length||busy} onClick={upload}>{busy?'Processing upload…':t.upload}</button>{progress>0&&<div className="progress" aria-label={`Upload ${progress}%`}><i style={{width:`${progress}%`}}/></div>}{notice&&<p className="notice" role="status">{notice}</p>}</section><section className="library"><div className="sectionHead"><div><p className="eyebrow">PRIVATE LIBRARY</p><h2>{t.documents}</h2></div><button onClick={()=>void loadDocuments()}>Refresh</button></div>{documents.length===0?<div className="empty">{t.empty}</div>:<div className="documentList">{documents.map(document=><article key={document.document_id}><span className="fileIcon">{document.original_name.split('.').pop()?.toUpperCase()}</span><div><b>{document.original_name}</b><small>{(document.size_bytes/1024).toFixed(1)} KB · {document.language_detected.toUpperCase()}</small>{document.error_message&&<em>{document.error_message}</em>}</div><span className={`status ${document.status}`}>{document.status}</span></article>)}</div>}</section></main></div>;
}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
